//! LLM conversation message types.

use serde::{Deserialize, Serialize};

/// Generate a fresh server-assigned message ID.
///
/// Used as the serde default for `Message::msg_id` so that messages persisted
/// before this field existed are stamped with a stable UUID on first load.
/// New messages built via `Message::user`, `Message::assistant`, etc. also
/// receive a fresh server-generated UUID rather than trusting any
/// LLM-provided identifier (which can collide across sessions or be reused).
fn new_msg_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// A message in an LLM conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Server-assigned unique message ID (UUID v4).
    ///
    /// Always generated by OpenFang at message creation time. LLM providers'
    /// own `id` fields are unreliable (different formats per provider, can
    /// collide across sessions, sometimes absent), so we never use them as the
    /// primary key. The provider-supplied ID, when present, is preserved in
    /// `provider_msg_id` for debugging only.
    ///
    /// Old sessions on disk that predate this field will deserialize with a
    /// freshly-generated UUID — they had no stable ID before, so this is a
    /// strict improvement.
    #[serde(default = "new_msg_id")]
    pub msg_id: String,
    /// Optional LLM-provided message identifier (e.g. Anthropic `msg_abc...`,
    /// OpenAI `chatcmpl-...`). Preserved for debugging/correlation only —
    /// never used as the primary identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_msg_id: Option<String>,
    /// The role of the sender.
    pub role: Role,
    /// The content of the message.
    pub content: MessageContent,
}

/// The role of a message sender in an LLM conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System prompt.
    System,
    /// Human user.
    #[default]
    User,
    /// AI assistant.
    Assistant,
}

/// Content of a message — can be simple text or structured blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    /// Simple text content.
    Text(String),
    /// Structured content blocks.
    Blocks(Vec<ContentBlock>),
}

impl Default for MessageContent {
    fn default() -> Self {
        MessageContent::Text(String::new())
    }
}

impl Default for Message {
    fn default() -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::User,
            content: MessageContent::Text(String::new()),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Source {
    Inline(#[serde(with = "inline_bytes")] Vec<u8>),
    Url(String),
    Stored(String),
    Uploaded { file_id: String, provider: String },
}

mod inline_bytes {
    use base64::Engine;
    use serde::{Deserializer, Serializer, de};

    pub fn serialize<S: Serializer>(bytes: &[u8], serializer: S) -> Result<S::Ok, S::Error> {
        match serializer.is_human_readable() {
            true => {
                serializer.serialize_str(&base64::engine::general_purpose::STANDARD.encode(bytes))
            }
            false => serializer.serialize_bytes(bytes),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Vec<u8>, D::Error> {
        struct Bytes;

        impl<'de> de::Visitor<'de> for Bytes {
            type Value = Vec<u8>;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("base64 text or raw bytes")
            }

            fn visit_str<E: de::Error>(self, text: &str) -> Result<Vec<u8>, E> {
                base64::engine::general_purpose::STANDARD
                    .decode(text)
                    .map_err(de::Error::custom)
            }

            fn visit_bytes<E: de::Error>(self, bytes: &[u8]) -> Result<Vec<u8>, E> {
                Ok(bytes.to_vec())
            }

            fn visit_byte_buf<E: de::Error>(self, bytes: Vec<u8>) -> Result<Vec<u8>, E> {
                Ok(bytes)
            }

            fn visit_seq<A: de::SeqAccess<'de>>(self, mut seq: A) -> Result<Vec<u8>, A::Error> {
                let mut bytes = Vec::with_capacity(seq.size_hint().unwrap_or_default());
                while let Some(byte) = seq.next_element()? {
                    bytes.push(byte);
                }
                Ok(bytes)
            }
        }

        deserializer.deserialize_any(Bytes)
    }
}

impl Source {
    pub fn inline(&self) -> Option<&[u8]> {
        match self {
            Source::Inline(bytes) => Some(bytes),
            _ => None,
        }
    }

    pub fn url(&self) -> Option<&str> {
        match self {
            Source::Url(url) => Some(url),
            _ => None,
        }
    }

    pub fn stored(&self) -> Option<&str> {
        match self {
            Source::Stored(id) => Some(id),
            _ => None,
        }
    }

    pub fn uploaded(&self) -> Option<(&str, &str)> {
        match self {
            Source::Uploaded { file_id, provider } => Some((file_id, provider)),
            _ => None,
        }
    }
}

/// A content block within a message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ContentBlock {
    /// A text block.
    #[serde(rename = "text")]
    Text {
        /// The text content.
        text: String,
        /// Provider-specific metadata (e.g. Gemini `thoughtSignature`).
        /// Opaque to the core — drivers read/write this to round-trip
        /// fields the provider requires on subsequent requests.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<serde_json::Value>,
    },
    #[serde(rename = "image")]
    Image {
        media_type: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        filename: Option<String>,
        #[serde(flatten)]
        source: Source,
    },
    #[serde(rename = "file")]
    File {
        media_type: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        filename: Option<String>,
        #[serde(flatten)]
        source: Source,
    },
    /// A tool use request from the assistant.
    #[serde(rename = "tool_use")]
    ToolUse {
        /// Unique ID for this tool use.
        id: String,
        /// The tool name.
        name: String,
        /// The tool input parameters.
        input: serde_json::Value,
        /// Provider-specific metadata (e.g. Gemini `thoughtSignature`).
        /// Opaque to the core — drivers read/write this to round-trip
        /// fields the provider requires on subsequent requests.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<serde_json::Value>,
    },
    /// A tool result from executing a tool.
    #[serde(rename = "tool_result")]
    ToolResult {
        /// The tool_use ID this result corresponds to.
        tool_use_id: String,
        /// The tool name (for Gemini FunctionResponse). Empty for legacy sessions.
        #[serde(default)]
        tool_name: String,
        /// The result content.
        content: ToolResultPayload,
        /// Whether the tool execution errored.
        is_error: bool,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        provenance: Vec<crate::ProvenanceSource>,
    },
    /// Extended thinking content block (model's reasoning trace).
    ///
    /// Preserved across turns so reasoning models retain state. Anthropic's
    /// extended thinking requires the `signature` to be echoed on resubmission;
    /// other providers (Gemini thought signatures, DeepSeek/Qwen
    /// `reasoning_content`, MiniMax inline `<think>`) round-trip via
    /// `provider_metadata` or by inlining into the assistant message body.
    #[serde(rename = "thinking")]
    Thinking {
        /// The thinking/reasoning text.
        thinking: String,
        /// Provider-issued signature required to resubmit thinking blocks
        /// (Anthropic extended thinking). `None` for providers that don't
        /// emit a signature.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
        /// Provider-specific metadata (e.g. `{"format": "reasoning_content"}`
        /// or `{"format": "inline_think"}` so the outbound driver knows how
        /// the upstream model originally delivered the reasoning).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<serde_json::Value>,
    },
    /// Anthropic redacted-thinking block — encrypted reasoning the model
    /// chose to hide. The `data` blob is opaque to us but MUST be echoed
    /// verbatim on subsequent turns, otherwise Anthropic rejects the
    /// resubmitted history. Only emitted by the Anthropic driver.
    #[serde(rename = "redacted_thinking")]
    RedactedThinking {
        /// Opaque encrypted reasoning payload from Anthropic.
        data: String,
    },
    /// Catch-all for unrecognized content block types (forward compatibility).
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolResultPayload {
    Inline(serde_json::Value),
    Artifact {
        id: String,
        preview: String,
        mime: String,
        size: u64,
    },
}

impl ToolResultPayload {
    pub fn inline(value: impl Into<serde_json::Value>) -> Self {
        ToolResultPayload::Inline(value.into())
    }

    pub fn text(&self) -> String {
        match self {
            ToolResultPayload::Inline(serde_json::Value::String(text)) => text.clone(),
            ToolResultPayload::Inline(value) => value.to_string(),
            ToolResultPayload::Artifact {
                id,
                preview,
                mime,
                size,
            } => format!("{preview}\n[full output stored as artifact {id} ({mime}, {size} bytes)]"),
        }
    }

    pub fn text_length(&self) -> usize {
        match self {
            ToolResultPayload::Inline(serde_json::Value::String(text)) => text.len(),
            ToolResultPayload::Inline(value) => value.to_string().len(),
            ToolResultPayload::Artifact { preview, .. } => preview.len(),
        }
    }
}

impl Default for ToolResultPayload {
    fn default() -> Self {
        ToolResultPayload::Inline(serde_json::Value::String(String::new()))
    }
}

impl From<&str> for ToolResultPayload {
    fn from(text: &str) -> Self {
        ToolResultPayload::Inline(serde_json::Value::String(text.to_string()))
    }
}

impl From<String> for ToolResultPayload {
    fn from(text: String) -> Self {
        ToolResultPayload::Inline(serde_json::Value::String(text))
    }
}

impl From<serde_json::Value> for ToolResultPayload {
    fn from(value: serde_json::Value) -> Self {
        ToolResultPayload::Inline(value)
    }
}

/// Allowed image media types.
const ALLOWED_IMAGE_TYPES: &[&str] = &["image/png", "image/jpeg", "image/gif", "image/webp"];

/// Maximum decoded image size (5 MB).
const MAX_IMAGE_BYTES: usize = 5 * 1024 * 1024;

/// Validate an image content block.
///
/// Checks that the media type is an allowed image format and the
/// base64 data doesn't exceed 5 MB when decoded (~7 MB base64).
pub fn validate_image(media_type: &str, data: &str) -> Result<(), String> {
    if !ALLOWED_IMAGE_TYPES.contains(&media_type) {
        return Err(format!(
            "Unsupported image type '{}'. Allowed: {}",
            media_type,
            ALLOWED_IMAGE_TYPES.join(", ")
        ));
    }
    // Base64 encodes 3 bytes into 4 chars, so max base64 len ≈ MAX_IMAGE_BYTES * 4/3
    let max_b64_len = MAX_IMAGE_BYTES * 4 / 3 + 4; // small padding allowance
    if data.len() > max_b64_len {
        return Err(format!(
            "Image too large: {} bytes base64 (max ~{} bytes for {} MB decoded)",
            data.len(),
            max_b64_len,
            MAX_IMAGE_BYTES / (1024 * 1024)
        ));
    }
    Ok(())
}

impl MessageContent {
    /// Create simple text content.
    pub fn text(content: impl Into<String>) -> Self {
        MessageContent::Text(content.into())
    }

    /// Get the total character length of text in this content.
    pub fn text_length(&self) -> usize {
        match self {
            MessageContent::Text(s) => s.len(),
            MessageContent::Blocks(blocks) => blocks
                .iter()
                .map(|b| match b {
                    ContentBlock::Text { text, .. } => text.len(),
                    ContentBlock::ToolResult { content, .. } => content.text_length(),
                    ContentBlock::Thinking { thinking, .. } => thinking.len(),
                    ContentBlock::ToolUse { name, input, .. } => {
                        name.len() + input.to_string().len()
                    }
                    ContentBlock::Image { .. }
                    | ContentBlock::File { .. }
                    | ContentBlock::RedactedThinking { .. }
                    | ContentBlock::Unknown => 0,
                })
                .sum(),
        }
    }

    /// Extract all text content as a single string.
    pub fn text_content(&self) -> String {
        match self {
            MessageContent::Text(s) => s.clone(),
            MessageContent::Blocks(blocks) => blocks
                .iter()
                .filter_map(|b| match b {
                    ContentBlock::Text { text, .. } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(""),
        }
    }
}

impl Message {
    /// Create a system message.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::System,
            content: MessageContent::Text(content.into()),
        }
    }

    /// Create a user message.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::User,
            content: MessageContent::Text(content.into()),
        }
    }

    /// Create a user message with structured content blocks (e.g. text + images).
    pub fn user_with_blocks(blocks: Vec<ContentBlock>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::User,
            content: MessageContent::Blocks(blocks),
        }
    }

    /// Create an assistant message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::Assistant,
            content: MessageContent::Text(content.into()),
        }
    }

    /// Create an assistant message with structured content blocks.
    ///
    /// Used to preserve `Thinking` blocks (with signatures and reasoning text)
    /// across persistence so reasoning models retain state between turns.
    pub fn assistant_with_blocks(blocks: Vec<ContentBlock>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::Assistant,
            content: MessageContent::Blocks(blocks),
        }
    }

    /// Attach a provider-supplied message ID (for debugging only).
    ///
    /// The server-generated `msg_id` remains the primary identifier — this
    /// records what the upstream LLM called the same message so we can
    /// correlate logs/traces with provider dashboards.
    pub fn with_provider_msg_id(mut self, provider_id: impl Into<String>) -> Self {
        self.provider_msg_id = Some(provider_id.into());
        self
    }
}

/// Why the LLM stopped generating.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model finished its turn.
    EndTurn,
    /// The model wants to use a tool.
    ToolUse,
    /// The model hit the token limit.
    MaxTokens,
    /// The model hit a stop sequence.
    StopSequence,
}

/// Token usage information from an LLM call.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens used for the input/prompt.
    pub input_tokens: u64,
    /// Tokens generated in the output.
    pub output_tokens: u64,
    #[serde(default)]
    pub cache_read_tokens: u64,
    #[serde(default)]
    pub cache_write_tokens: u64,
}

impl TokenUsage {
    /// Total tokens used.
    pub fn total(&self) -> u64 {
        self.input_tokens + self.output_tokens
    }

    pub fn add(&mut self, other: &TokenUsage) {
        self.input_tokens += other.input_tokens;
        self.output_tokens += other.output_tokens;
        self.cache_read_tokens += other.cache_read_tokens;
        self.cache_write_tokens += other.cache_write_tokens;
    }
}

/// Reply directives extracted from agent output.
///
/// These control how the response is delivered back to the user/channel:
/// - `reply_to`: reply to a specific message ID
/// - `current_session`: reply in the current session
/// - `silent`: suppress the response entirely
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ReplyDirectives {
    /// Reply to a specific message ID.
    pub reply_to: Option<String>,
    /// Reply in the current session.
    pub current_session: bool,
    /// Suppress the response from being sent.
    pub silent: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_creation() {
        let msg = Message::user("Hello");
        assert_eq!(msg.role, Role::User);
        match msg.content {
            MessageContent::Text(text) => assert_eq!(text, "Hello"),
            _ => panic!("Expected text content"),
        }
    }

    #[test]
    fn test_token_usage() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
            ..Default::default()
        };
        assert_eq!(usage.total(), 150);

        let old_log: TokenUsage =
            serde_json::from_str(r#"{"input_tokens":100,"output_tokens":50}"#).unwrap();
        assert_eq!(old_log.cache_read_tokens, 0);
        assert_eq!(old_log.cache_write_tokens, 0);

        let mut sum = TokenUsage::default();
        sum.add(&TokenUsage {
            input_tokens: 1,
            output_tokens: 2,
            cache_read_tokens: 3,
            cache_write_tokens: 4,
        });
        sum.add(&old_log);
        assert_eq!(sum.input_tokens, 101);
        assert_eq!(sum.cache_read_tokens, 3);
        assert_eq!(sum.cache_write_tokens, 4);
    }

    #[test]
    fn test_validate_image_valid() {
        assert!(validate_image("image/png", "iVBORw0KGgo=").is_ok());
        assert!(validate_image("image/jpeg", "data").is_ok());
        assert!(validate_image("image/gif", "data").is_ok());
        assert!(validate_image("image/webp", "data").is_ok());
    }

    #[test]
    fn test_validate_image_bad_type() {
        let err = validate_image("image/svg+xml", "data").unwrap_err();
        assert!(err.contains("Unsupported image type"));
        let err = validate_image("text/plain", "data").unwrap_err();
        assert!(err.contains("Unsupported image type"));
    }

    #[test]
    fn test_validate_image_too_large() {
        let huge = "A".repeat(8_000_000); // ~6MB base64
        let err = validate_image("image/png", &huge).unwrap_err();
        assert!(err.contains("too large"));
    }

    #[test]
    fn test_content_block_image_serde() {
        let block = ContentBlock::Image {
            media_type: "image/png".to_string(),
            filename: None,
            source: Source::Inline(b"raw bytes".to_vec()),
        };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(json["type"], "image");
        assert_eq!(json["media_type"], "image/png");
        assert_eq!(json["inline"], "cmF3IGJ5dGVz");
        assert!(json.get("filename").is_none());
    }

    #[test]
    fn inline_bytes_are_base64_in_json_and_raw_in_msgpack() {
        let block = ContentBlock::Image {
            media_type: "image/png".to_string(),
            filename: None,
            source: Source::Inline(b"\x89PNG\r\n\x1a\n".to_vec()),
        };

        let json = serde_json::to_string(&block).unwrap();
        assert!(json.contains("iVBORw0KGgo="), "{json}");
        let back: ContentBlock = serde_json::from_str(&json).unwrap();
        assert_eq!(
            source_of(&back).and_then(Source::inline),
            Some(b"\x89PNG\r\n\x1a\n".as_slice())
        );

        let packed = rmp_serde::to_vec_named(&block).unwrap();
        assert!(
            !String::from_utf8_lossy(&packed).contains("iVBORw"),
            "msgpack must carry the bytes, not a base64 string"
        );
        let back: ContentBlock = rmp_serde::from_slice(&packed).unwrap();
        assert_eq!(
            source_of(&back).and_then(Source::inline),
            Some(b"\x89PNG\r\n\x1a\n".as_slice())
        );
        assert!(
            packed.len() < json.len(),
            "raw bytes must beat base64: {} packed vs {} json",
            packed.len(),
            json.len()
        );
    }

    fn source_of(block: &ContentBlock) -> Option<&Source> {
        match block {
            ContentBlock::Image { source, .. } | ContentBlock::File { source, .. } => Some(source),
            _ => None,
        }
    }

    #[test]
    fn each_source_names_a_file_a_different_way() {
        let cases = [
            (
                Source::Inline(b"raw bytes".to_vec()),
                serde_json::json!({ "inline": "cmF3IGJ5dGVz" }),
            ),
            (
                Source::Stored("art-abc".to_string()),
                serde_json::json!({ "stored": "art-abc" }),
            ),
            (
                Source::Uploaded {
                    file_id: "file-xyz".to_string(),
                    provider: "anthropic".to_string(),
                },
                serde_json::json!({ "uploaded": { "file_id": "file-xyz", "provider": "anthropic" } }),
            ),
        ];

        for (source, expected) in cases {
            let block = ContentBlock::File {
                media_type: "application/pdf".to_string(),
                filename: Some("invoice.pdf".to_string()),
                source: source.clone(),
            };
            let json = serde_json::to_value(&block).unwrap();
            assert_eq!(json["type"], "file");
            assert_eq!(json["filename"], "invoice.pdf");
            for (key, value) in expected.as_object().unwrap() {
                assert_eq!(&json[key], value, "{source:?}");
            }

            let back: ContentBlock = serde_json::from_value(json).unwrap();
            let ContentBlock::File { source: back, .. } = back else {
                panic!("expected a File block");
            };
            assert_eq!(back, source);
        }
    }

    #[test]
    fn a_provider_handle_says_whose_it_is() {
        let source = Source::Uploaded {
            file_id: "file-xyz".to_string(),
            provider: "anthropic".to_string(),
        };
        assert_eq!(source.uploaded(), Some(("file-xyz", "anthropic")));
        assert!(source.inline().is_none());
        assert!(source.stored().is_none());
    }

    #[test]
    fn tool_result_payload_round_trips_both_arms_in_json_and_msgpack() {
        let inline = ToolResultPayload::inline(serde_json::json!({ "inline": "tricky" }));
        let artifact = ToolResultPayload::Artifact {
            id: "art-1".into(),
            preview: "first bytes…".into(),
            mime: "application/json".into(),
            size: 12_345,
        };
        for payload in [inline, artifact] {
            let json = serde_json::to_value(&payload).unwrap();
            let back: ToolResultPayload = serde_json::from_value(json).unwrap();
            assert_eq!(back, payload);

            let bytes = rmp_serde::to_vec_named(&payload).unwrap();
            let back: ToolResultPayload = rmp_serde::from_slice(&bytes).unwrap();
            assert_eq!(back, payload);
        }
    }

    #[test]
    fn tool_result_payload_text_projects_each_arm() {
        assert_eq!(ToolResultPayload::inline("hi").text(), "hi");
        assert_eq!(
            ToolResultPayload::inline(serde_json::json!({ "a": 1 })).text(),
            r#"{"a":1}"#
        );
        let artifact = ToolResultPayload::Artifact {
            id: "art-9".into(),
            preview: "head".into(),
            mime: "text/plain".into(),
            size: 9,
        };
        let text = artifact.text();
        assert!(text.starts_with("head\n"));
        assert!(text.contains("art-9"));
        assert!(text.contains("9 bytes"));
    }

    #[test]
    fn test_content_block_unknown_deser() {
        let json = serde_json::json!({"type": "future_block_type"});
        let block: ContentBlock = serde_json::from_value(json).unwrap();
        assert!(matches!(block, ContentBlock::Unknown));
    }

    #[test]
    fn test_thinking_block_roundtrip_preserves_signature() {
        // Anthropic extended thinking — the signature MUST round-trip through
        // serde so it can be echoed on the next request.
        let block = ContentBlock::Thinking {
            thinking: "Let me reason about this carefully...".to_string(),
            signature: Some("sig_abc123_anthropic_extended_thinking".to_string()),
            provider_metadata: None,
        };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(json["type"], "thinking");
        assert_eq!(json["signature"], "sig_abc123_anthropic_extended_thinking");

        // Round-trip through serialize → deserialize (e.g. SQLite session blob)
        let serialized = serde_json::to_string(&block).unwrap();
        let restored: ContentBlock = serde_json::from_str(&serialized).unwrap();
        match restored {
            ContentBlock::Thinking {
                thinking,
                signature,
                ..
            } => {
                assert_eq!(thinking, "Let me reason about this carefully...");
                assert_eq!(
                    signature.as_deref(),
                    Some("sig_abc123_anthropic_extended_thinking")
                );
            }
            _ => panic!("expected Thinking block"),
        }
    }

    #[test]
    fn test_thinking_block_roundtrip_with_provider_metadata() {
        // OpenAI-compat models (DeepSeek-R1, Qwen3, MiniMax) — record the
        // wire format so the outbound driver knows whether to re-emit as
        // `reasoning_content` or inline `<think>` tags.
        let block = ContentBlock::Thinking {
            thinking: "step-by-step analysis".to_string(),
            signature: None,
            provider_metadata: Some(serde_json::json!({"format": "inline_think"})),
        };
        let serialized = serde_json::to_string(&block).unwrap();
        let restored: ContentBlock = serde_json::from_str(&serialized).unwrap();
        match restored {
            ContentBlock::Thinking {
                thinking,
                signature,
                provider_metadata,
            } => {
                assert_eq!(thinking, "step-by-step analysis");
                assert!(signature.is_none());
                let meta = provider_metadata.expect("provider_metadata preserved");
                assert_eq!(meta["format"], "inline_think");
            }
            _ => panic!("expected Thinking block"),
        }
    }

    #[test]
    fn test_thinking_block_legacy_deser() {
        // Existing sessions on disk only have `{"type": "thinking", "thinking": "..."}`.
        // The new fields must be optional so old payloads still load.
        let json = serde_json::json!({"type": "thinking", "thinking": "old session reasoning"});
        let block: ContentBlock = serde_json::from_value(json).unwrap();
        match block {
            ContentBlock::Thinking {
                thinking,
                signature,
                provider_metadata,
            } => {
                assert_eq!(thinking, "old session reasoning");
                assert!(signature.is_none());
                assert!(provider_metadata.is_none());
            }
            _ => panic!("expected Thinking block"),
        }
    }

    #[test]
    fn test_assistant_with_blocks_preserves_thinking() {
        // A complete round-trip: build an assistant turn that mixes Thinking +
        // Text (the shape we'll store after fix) and confirm the Thinking
        // block survives serialization (msgpack is what session.rs uses; JSON
        // exercises the same serde path).
        let msg = Message::assistant_with_blocks(vec![
            ContentBlock::Thinking {
                thinking: "Internal reasoning".to_string(),
                signature: Some("sig_xyz".to_string()),
                provider_metadata: None,
            },
            ContentBlock::Text {
                text: "Hello!".to_string(),
                provider_metadata: None,
            },
        ]);
        let bytes = rmp_serde::to_vec_named(&msg).expect("msgpack encode");
        let restored: Message = rmp_serde::from_slice(&bytes).expect("msgpack decode");
        match restored.content {
            MessageContent::Blocks(blocks) => {
                assert_eq!(blocks.len(), 2);
                match &blocks[0] {
                    ContentBlock::Thinking {
                        thinking,
                        signature,
                        ..
                    } => {
                        assert_eq!(thinking, "Internal reasoning");
                        assert_eq!(signature.as_deref(), Some("sig_xyz"));
                    }
                    _ => panic!("expected Thinking first"),
                }
            }
            _ => panic!("expected Blocks content"),
        }
    }

    #[test]
    fn test_msg_id_is_server_assigned_uuid() {
        // Every constructor must stamp a server-side UUID — never trust the
        // LLM-provided ID as the primary key.
        let a = Message::user("hello");
        let b = Message::user("hello");
        assert_ne!(a.msg_id, b.msg_id, "msg_id must be unique per message");
        // Must parse as a valid UUID v4.
        let parsed = uuid::Uuid::parse_str(&a.msg_id).expect("msg_id must be a valid UUID");
        assert_eq!(parsed.get_version_num(), 4, "msg_id must be UUID v4");
        // Provider id defaults to None.
        assert!(a.provider_msg_id.is_none());
    }

    #[test]
    fn test_provider_msg_id_is_recorded_but_not_primary() {
        // The LLM-supplied identifier is preserved for debugging only — the
        // server-generated `msg_id` is unchanged and remains the primary key.
        let msg = Message::assistant("hi").with_provider_msg_id("msg_abc123_anthropic_collidable");
        assert_eq!(
            msg.provider_msg_id.as_deref(),
            Some("msg_abc123_anthropic_collidable")
        );
        // msg_id is still the server UUID, NOT the provider string.
        assert_ne!(msg.msg_id, "msg_abc123_anthropic_collidable");
        assert!(uuid::Uuid::parse_str(&msg.msg_id).is_ok());
    }

    #[test]
    fn test_legacy_message_deser_gets_fresh_msg_id() {
        // Sessions persisted before this field existed must still load — the
        // serde default stamps a fresh UUID so callers always see a stable ID.
        let legacy = serde_json::json!({
            "role": "user",
            "content": "old session message"
        });
        let restored: Message = serde_json::from_value(legacy).unwrap();
        assert!(
            uuid::Uuid::parse_str(&restored.msg_id).is_ok(),
            "legacy payloads must deserialize with a server-stamped UUID"
        );
        assert!(restored.provider_msg_id.is_none());
    }

    #[test]
    fn test_msg_id_survives_msgpack_roundtrip() {
        // SessionStore persists via rmp_serde — make sure msg_id round-trips.
        let original = Message::user("hello").with_provider_msg_id("msg_xyz");
        let bytes = rmp_serde::to_vec_named(&original).expect("encode");
        let restored: Message = rmp_serde::from_slice(&bytes).expect("decode");
        assert_eq!(restored.msg_id, original.msg_id);
        assert_eq!(restored.provider_msg_id.as_deref(), Some("msg_xyz"));
    }

    #[test]
    fn test_user_with_blocks() {
        let blocks = vec![
            ContentBlock::Text {
                text: "What is in this image?".to_string(),
                provider_metadata: None,
            },
            ContentBlock::Image {
                media_type: "image/jpeg".to_string(),
                filename: None,
                source: Source::Inline(b"raw bytes".to_vec()),
            },
        ];
        let msg = Message::user_with_blocks(blocks);
        assert_eq!(msg.role, Role::User);
        match msg.content {
            MessageContent::Blocks(ref b) => {
                assert_eq!(b.len(), 2);
                assert!(
                    matches!(&b[0], ContentBlock::Text { text, .. } if text == "What is in this image?")
                );
                assert!(
                    matches!(&b[1], ContentBlock::Image { media_type, .. } if media_type == "image/jpeg")
                );
            }
            _ => panic!("Expected blocks content"),
        }
    }
}
